### ISSUE TITLE
[FEATURE REQUEST] Ping another person with @ and then another person receive notification about ping

### ISSUE THREAD

**Issue by DmytroLitvinov** [KafetzisThomas/Chatterbox#10]
Could be related kinda to "silent" mode, but when ping, it shows on conversation something like "red" alert instead of grey If I muted it.

**Comment by KafetzisThomas** [comment]
Cool idea! How are you thinking of implementing it? My guess is that when one user pings the other, an email with the message content could be sent, acting like a notification. Since the chat groups are 1-on-1, unlike Discord where multiple people join a single channel, this approach might work well. Also, it could be great if the color of the chat message box to red or orange, for example, to differentiate it from other types of messages.

What do you think about this approach?

**Comment by KafetzisThomas** [comment]
You can access the app through the live demo link provided in the README if you haven’t had a chance to set it up locally.

Regarding the notification feature you mentioned, **implementing push notifications isn’t feasible since this is a web app, not a native mobile app.** It can only be added as a shortcut on your phone and won't support push notifications like a mobile app would. However, an alternative approach could be to send email notifications when a user pings you in a chat room. Additionally, I could enhance the chat UI by highlighting messages to make them more noticeable. This way, it could serve as an effective `alert mechanism`.

I've actually started working on this feature on a new branch, just added an email field to the registration and account forms:
https://github.com/KafetzisThomas/Chatterbox/commits/ping-functionality/
